version: '2'
services:
    sftpbot-app:
        image: sftpbot
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://sftpbot-mysql:3306/sftpbot?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
        volumes:
            - ~/volumes/jhipster/sftpbot/:/root

    sftpbot-mysql:
        extends:
            file: mysql.yml
            service: sftpbot-mysql
    sftpbot-sftp:
        extends:
            file: sftp.yml
            service: sftpbot-sftp
